### PR TITLE
Catch up with latest Reactor snapshot

### PR DESCRIPTION
**Pull request by rstoyanchev**

### CODE REVIEW

**Comment by rstoyanchev** [comment]
BTW "Big List in DATA-DRIVEN mode" doesn't work for me. Is it supposed to?

**Comment by danielfernandez** [comment]
@rstoyanchev it should now. It worked before with the old snapshot of Reactor, but once updated it simply stopped after a couple of requests to the flow. 

I changed the `Flux.create(...)` call I was using there to a `Flux.generate(...)` in a similar way to what you did for the buffered flow creation and now it works again.

**Comment by danielfernandez** [comment]
By the way... not sure of the difference between `create(...)` and `generate(...)` there. Obviously one works for me now and the other doesn't :) but... generally speaking... why is this?

**Comment by rstoyanchev** [comment]
I'm not too certain of the difference myself. These methods were recently refactored as well. I must have stumbled onto the right answer TBH. I believe `generate` calls your consumer once per requested item while `create` calls you whenever there is a request and you can check the actual request count via `emitter.requestedFromDownstream()`. The Javadoc seems unhelpful and possibly outdated on `create` in particular. @smaldini does that description sound right?

**Comment by smaldini** [comment]
Before M4 there will be another pass on javadoc to fix these. Don't hesitate, also EmitterProcessor and the Processor space is a specific focus of the M4, as create/generate.

I'll review more closely later, I have a workshop today and I need to produce some decision matrix soon for operators to help. If @akarnokd you have also spare time it would be nicesome. I think having a real reactive templating solution is full of promises so we will help as much as we can spare @danielfernandez !

**Comment by smaldini** [comment]
Regarding create vs generate, in M4 generate simply allows you to use a callback per demand decrement and to pass a context (much like scan/reduce) from the function result. Flux#create allows to be "waken up" when there is a request but you manage how much you send yourself.

**Comment by danielfernandez** [comment]
Awesome @smaldini, thanks. 

Just wanted to note though that Thymeleaf is not a _real reactive templating solution_ as it is not developed in a reactive way, nor its architecture is reactive. Some parts are actually synchronous and blocking, mainly resource resolution --which uses blocking I/O-- and cache access --which uses `ConcurrentHashMap`--. However, in most scenarios the template cache is used so this latter is the only blocking part of a template execution process.

So in order to be 100% fair this integration does not turn Thymeleaf into a _reactive template engine_ --I don't even know if such thing exists :)--, but simply makes Thymeleaf _very reactive-friendly_ and able to work as a step of a reactive data flow (or `Flux`, `Publisher`, `Observable` or whatever the name :))

**Comment by smaldini** [comment]
Reactive Streams is not totally orthogonal to blocking, and Rx or Reactor are providing proper execution strategies developers can pick vs imposing an execution model.
What it could bring in terms of predictable capacity is however huge, the QoS introduced by the flow control tells how much your application can do at a given time T.

Non Blocking means that it doesn't negatively impact the caller, reading from memory doesn't, reading from IO does. But again that's a totally acceptable behavior in Rx/Reactor to have a blocking block if you isolate it later (or hint the user to do so if they want) with thread boundaries : publishOn/subscribeOn

**Comment by danielfernandez** [comment]
Alright, thanks a lot for the explanation :)

**Comment by smaldini** [comment]
Thanks a lot for your effort ! We'll get back to you later on and we can iterate also on the implications of reactive. I think it's a total new territory and we will come up with interesting observations anyway, especially if the template play nicely with Publisher based variable ! That already needs a heck of deferring to manage 👍

**Pull request merged**
